# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.boot_timeout = 600 # 10 minutes
  (1..3).each do |i|
    config.vm.synced_folder '.', '/vagrant', disabled: true
    config.vm.define "ansibledemo#{i}" do |ansibledemo|
      ansibledemo.vm.box = "ubuntu/focal64"
      ansibledemo.vm.hostname = "ansibledemo#{i}"
      ansibledemo.vm.network "forwarded_port", guest: 80, host: 8080+i, host_ip: "127.0.0.1"
      ansibledemo.vm.provider "virtualbox" do |vb|
        vb.memory = "2048"
        vb.cpus = "2"
        vb.name = "ansibledemo#{i}"
        vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
      end
    end
  end
end
