name: nodejs-todo-sample
services:
  nodejs-todo-mongo:
    restart: always
    build: ../../NodeJS/ToDoNodeJS-MongoDB
    environment:
      - DB_URL=mongodb
      - DB_NAME=test
    links:
      - mongodb
    expose:
      - "3000"

  nodejs-todo-mysql:
    restart: always
    build: ../../NodeJS/ToDoNodeJS-MySQL
    environment:
      - DB_HOST=mysql-db
      - DB_USER=test
      - DB_PASSWORD=test
      - DB_NAME=test
    depends_on:
        mysql-db:
          condition: service_healthy
          restart: true
    expose:
      - "3000"

  reverse-proxy:
    image: nginx:latest
    links:
      - nodejs-todo-mysql
      - nodejs-todo-mongo
    volumes:
      - ./nodejs-todo.conf:/etc/nginx/conf.d/default.conf    
    ports:
      - "8080:80"

  mongodb:
    image: mongo:5.0.27
    volumes:
      - mongoddb-vol:/var/lib/mysql
    expose:
      - "27017"

  mysql-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=test
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    expose:
      - "3306"
    volumes:
      - mysqldb-vol:/var/lib/mysql
      - ./init.sql:/data/application/init.sql
    command: --mysql_native_password=ON --init-file /data/application/init.sql

volumes:
  mongoddb-vol:
    external: false
  mysqldb-vol:
