Vagrant.configure("2") do |config|
  # Define Ubuntu servers
  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "bigdeal/mysql57"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "mysql"
    end
  end

  config.vm.define "mongodb" do |mongodb|
    mongodb.vm.box = "ubuntu/bionic64"
    mongodb.vm.hostname = "mongodb"
    mongodb.vm.network "forwarded_port", guest: 27107, host: 27107
    mongodb.vm.provision "file", source: "./mongodb_setup.sh", destination: "/tmp/mongodb_setup.sh"
    mongodb.vm.provision "shell", inline: "mv /tmp/*.sh /opt/ && chmod +x /opt/*.sh"
    mongodb.vm.provision "shell", path: "./mongodb_setup.sh"
    mongodb.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      vb.name = "mongodb"
    end
  end


end