---
- hosts: "{{ host_group }}"
  become: true

  tasks:
    - name: Set service name and target group based on host_group
      set_fact:
        docker_compose_path: "{{ '/home/ec2-user/PCC-DevOps-Bootcamp/Jenkins/Blue-Green-Deployment/green-mongo' if host_group == 'green_tg' else '/home/ec2-user/PCC-DevOps-Bootcamp/Jenkins/Blue-Green-Deployment/blue-mysql' }}"

    - name: Update the repository
      git:
        repo: "{{ GITHUB_REPO }}"
        dest: /home/ec2-user/PCC-DevOps-Bootcamp
        refspec: "+refs/heads/jenkins:refs/remotes/origin/jenkins"

    - name: Checkout to the jenkins branch
      shell: |
        git checkout jenkins
        git reset --hard origin/jenkins
      args:
        chdir: /home/ec2-user/PCC-DevOps-Bootcamp

    - name: Run docker-compose down
      shell: docker-compose down
      args:
        chdir: "{{ docker_compose_path }}"

    - name: Run docker-compose up with build
      shell: docker-compose up -d --no-deps --build
      args:
        chdir: "{{ docker_compose_path }}"
