- hosts: all
  become: true

  tasks:
    - name: Install Git and Docker
      yum:
        name:
          - git
          - docker
        state: present

    - name: Start Docker service
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to Docker group
      user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "0755"
      tags:
        - install_docker_compose

    - name: Configure Git user name
      git_config:
        name: user.name
        value: "Your Name"

    - name: Configure Git user email
      git_config:
        name: user.email
        value: "your.email@example.com"

    - name: Clone Git repository
      become_user: ec2-user
      git:
        # TODO: Replace <your github username> with your own github user name
        repo: https://github.com/<your github username>/PCC-DevOps-Bootcamp
        dest: /home/ec2-user/PCC-DevOps-Bootcamp
        force: yes
      tags:
        - update_git
