pipeline {
  agent any
  parameters {
    choice (name: 'chooseNode', choices: ['Green', 'Blue'], description: 'Choose which Environment to Deploy: ')
  }
  environment {
    listenerARN = 'arn:aws:elasticloadbalancing:us-east-1:773314055569:loadbalancer/app/blue-green-alb/e66a44af6d7d6725'
    blueARN = 'arn:aws:elasticloadbalancing:us-east-1:773314055569:targetgroup/blue-tg/fda570ba9fa0ba4b'
    greenARN = 'arn:aws:elasticloadbalancing:us-east-1:773314055569:targetgroup/green-tg/e41e1918562904c9'
    REPO_URL = 'https://github.com/kjakedev/PCC-DevOps-Bootcamp'
    REPO_DIR = '/home/ec2-user/PCC-DevOps-Bootcamp'
    AWS_CREDENTIALS_ID = 'aws-credentials'
  }
  stages {
    stage('Deployment Started') {
      parallel {
        stage('Green') {
          when {
            expression {
              params.chooseNode == 'Green'
            }
          }
          stages {
            stage('Offloading Green') {
              steps {
                withCredentials([
                  usernamePassword(
                    credentialsId: "${AWS_CREDENTIALS_ID}",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                  )
                ]) {
                  sh """
                    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY} aws elbv2 modify-listener --listener-arn ${listenerARN} --default-actions '[{"Type": "forward","Order": 1,"ForwardConfig": {"TargetGroups": [{"TargetGroupArn": "${greenARN}", "Weight": 0 },{"TargetGroupArn": "${blueARN}", "Weight": 1 }],"TargetGroupStickinessConfig": {"Enabled": true,"DurationSeconds": 1}}}]'
                  """
                }
              }
            }
            stage('Run on all green-tg nodes') {
              steps {
                node('green-tg') {
                  dir("${REPO_DIR}") {
                    git branch: 'jenkins', url: "${REPO_URL}"
                  }
                  dir("${REPO_DIR}/Jenkins/Blue-Green-Deployment/green-mongo") {
                    sh 'docker-compose -d --no-deps --build green-nodejs-mongo'
                  }
                }
              }
            }
          }
        }
        stage('Blue') {
          when {
            expression {
              params.chooseNode == 'Blue'
            }
          }
          stages {
            stage('Offloading Blue') {
              steps {
                withCredentials([
                  usernamePassword(
                    credentialsId: "${AWS_CREDENTIALS_ID}",
                    accessKeyVariable: 'AWS_ACCESS_KEY_ID',
                    secretKeyVariable: 'AWS_SECRET_ACCESS_KEY'
                  )
                ]) {
                  sh """
                    AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY} AWS_SECRET_ACCESS_KEY=${AWS_SECRET_KEY} aws elbv2 modify-listener --listener-arn ${listenerARN} --default-actions '[{"Type": "forward","Order": 1,"ForwardConfig": {"TargetGroups": [{"TargetGroupArn": "${greenARN}", "Weight": 1 },{"TargetGroupArn": "${blueARN}", "Weight": 0 }],"TargetGroupStickinessConfig": {"Enabled": true,"DurationSeconds": 1}}}]'
                  """
                }
              }
            }
            stage('Run on all blue-tg nodes') {
              steps {
                node('blue-tg') {
                  dir("${REPO_DIR}") {
                    git branch: 'jenkins', url: "${REPO_URL}"
                  }
                  dir("${REPO_DIR}/Jenkins/Blue-Green-Deployment/blue-mysql") {
                    sh 'docker-compose -d --no-deps --build blue-nodejs-mysql'
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}