Vagrant.configure("2") do |config|
  # Define Ubuntu servers
  config.vm.define "mysql" do |mysql|
    mysql.vm.box = "bigdeal/mysql57"
    mysql.vm.hostname = "mysql"
    mysql.vm.network "forwarded_port", guest: 3306, host: 3306
    mysql.vm.network "private_network", ip: "192.1.1.11", virtualbox__intnet: "private_net"
    mysql.vm.provision "shell", inline:  "mysql -u root -proot -e \"CREATE DATABASE test; CREATE USER 'test'@'%' IDENTIFIED WITH mysql_native_password BY 'test'; GRANT ALL PRIVILEGES ON *.* TO 'test'@'%';\""
    mysql.vm.provision "shell", inline:  "mysql -u root -proot -e \"SHOW DATABASES;\""
    mysql.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "1"
      vb.name = "mysql"
    end
  end

  config.vm.define "python" do |python|
    python.vm.box = "ubuntu/focal64"
    python.vm.hostname = "python"
    python.vm.network "forwarded_port", guest: 3000, host: 3000, host_ip: "127.0.0.1"
    python.vm.network "private_network", ip: "192.1.1.10", virtualbox__intnet: "private_net"
    python.vm.provision "file", source: "./python_setup.sh", destination: "/tmp/python_setup.sh"
    python.vm.provision "shell", inline: "mv /tmp/*.sh /opt/ && chmod +x /opt/*.sh"
    python.vm.provision "shell", privileged: false, path: "./python_setup.sh"
    python.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = "2"
      vb.name = "python"
    end
  end


end