Vagrant.configure("2") do |config|
	# define client2
  config.vm.define "client2" do |client2|
    client2.vm.box = "bento/centos-stream-9"
    client2.vm.network "private_network", ip: "10.160.2.12", virtualbox__intnet: "private_net1"
    client2.vm.hostname = "client2"
    client2.vm.provider "virtualbox" do |vb|
      vb.name = "client2"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
  
  # Define pfSense firewall
  config.vm.define "pfsense" do |pfsense|
    pfsense.vm.guest = :freebsd
    pfsense.vm.box = "ksklareski/pfsense-ce"
    pfsense.vm.hostname = "pfsense"
    pfsense.ssh.shell = 'sh'
    pfsense.ssh.insert_key = false
    pfsense.vm.network "private_network", ip: "10.160.2.1", virtualbox__intnet: "private_net1"
    pfsense.vm.network "forwarded_port", guest: 80, host: 8080
    pfsense.vm.provider "virtualbox" do |vb|
        vb.name = "pfsense"
        vb.memory = "1024"
        vb.cpus = "1"
    end
  end
  end